name: wifi
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  wifi_iot: ^0.3.19+1
  network_info_plus: ^6.0.2
  connectivity_plus: ^6.0.5
  wifi_scan: ^0.4.1+1
  http: ^1.2.2
  #  For device info
  shared_preferences: ^2.3.2
  unique_identifier: ^0.3.0
  package_info_plus: ^8.0.3
  device_info_plus: ^11.0.0
  safe_device: ^1.1.9
  geocoding: ^3.0.0
  dart_ipify: ^1.1.1
  #  for charts
  fl_chart: ^0.69.0

  permission_handler: ^11.3.1
  provider: ^6.0.5
  #loading
  loading_animation_widget: ^1.2.0+4
  #firebase
  firebase_core: ^3.6.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  #test
  flutter_internet_speed_test:
    path: ./modules/flutter_internet_speed_test
  kdgaugeview: ^1.0.5
  #pdf
  pdf: ^3.11.1
  share_plus: ^10.0.3
  path_provider: ^2.1.2
  screenshot: ^3.0.0
#  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  index_generator: ^3.3.3
  logger: ^2.0.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/

